-- Box messages.
-- "open_box", {}: open the box shortly, and close it 2 seconds later.

local function close_box(self)
	self.open = false
	msg.post("#sprite_open", "disable")
	msg.post("#sprite", "enable")
end

local function open_box(self)
	self.open = true
	msg.post("#sprite_open", "enable")
	msg.post("#sprite", "disable")
end


function init(self)
	close_box(self)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("open_box") then
		open_box(self)
	end
end